export interface Question {
  id: string;
  chapterId: string;
  level: "beginner" | "intermediate" | "advanced" | "expert";
  prompt: string;
  choices: string[];
  answer: number;
  explanation: string;
}

export const questions: Question[] = [
  { id: "q1", chapterId: "hello-go", level: "beginner",
    prompt: "You write a function named `helper` in package `util`. From another package you try to call `util.helper()` and the compiler refuses. Why?",
    choices: ["Go requires an explicit `export` keyword.", "Lowercase identifiers are package-private; only capitalized names are exported.", "You need to add `helper` to go.mod.", "Cross-package calls must go through an interface."],
    answer: 1, explanation: "Visibility in Go is encoded in the case of the first letter. `helper` is unexported; `Helper` would be callable from outside the package." },
  { id: "q2", chapterId: "hello-go", level: "beginner",
    prompt: "What does `go run main.go` do that `go build` does not?",
    choices: ["It produces a smaller binary.", "It executes immediately and doesn't leave a binary on disk.", "It downloads dependencies.", "It runs tests in addition to compiling."],
    answer: 1, explanation: "`go run` compiles to a temporary file and executes it. `go build` produces a persistent binary." },
  { id: "q3", chapterId: "hello-go", level: "beginner",
    prompt: "Which format verb in fmt.Printf prints any value in its default format?",
    choices: ["%s", "%d", "%v", "%T"],
    answer: 2, explanation: "`%v` is the catch-all — it works for any type. `%T` prints the type name. `%s` is strings, `%d` is integers." },
  { id: "q4", chapterId: "types-and-variables", level: "beginner",
    prompt: "What is the value of `var score int` declared without initialization?",
    choices: ["nil", "undefined", "0", "A compile error — Go requires initialization."],
    answer: 2, explanation: "Go's zero-value rule guarantees `int` starts at 0, `string` at \"\", `bool` at false, pointers at nil." },
  { id: "q5", chapterId: "types-and-variables", level: "beginner",
    prompt: "Why can `const pi = 3.14159` be assigned to both `float32` and `float64`?",
    choices: ["Go silently converts numeric types at runtime.", "Constants can be untyped; they take on the type required by the surrounding expression.", "`float32` and `float64` are the same type.", "The `const` keyword disables type checking."],
    answer: 1, explanation: "Untyped constants keep their abstract numeric nature until pinned to a concrete type by use." },
  { id: "q6", chapterId: "types-and-variables", level: "beginner",
    prompt: "You try `var x int = 3.5`. What does the compiler do?",
    choices: ["Accepts it and truncates to 3.", "Rejects it — 3.5 cannot be represented as int without explicit conversion.", "Rounds to 4.", "Stores as float64 silently."],
    answer: 1, explanation: "Go never implicitly converts between numeric types. You must write `int(3.5)` explicitly, which truncates to 3." },
  { id: "q7", chapterId: "control-flow", level: "beginner",
    prompt: "Which keyword does Go use to write a 'while' loop?",
    choices: ["while", "loop", "for", "until"],
    answer: 2, explanation: "`for cond { ... }` is Go's while. There is only one loop keyword." },
  { id: "q8", chapterId: "control-flow", level: "beginner",
    prompt: "When ranging over a string `for i, r := range s`, what type is `r`?",
    choices: ["byte (uint8)", "rune (int32) — a Unicode code point", "string", "int"],
    answer: 1, explanation: "`range` on a string decodes UTF-8 and yields runes. Indexing `s[i]` gives bytes — which breaks on non-ASCII." },
  { id: "q9", chapterId: "functions-errors", level: "intermediate",
    prompt: "Why does Go not have exceptions?",
    choices: ["The runtime is too small.", "Returning errors as values makes failure explicit in the type signature — invisible control flow was rejected.", "Exceptions are too slow.", "They weren't ready for Go 1.0."],
    answer: 1, explanation: "`(T, error)` puts failure in the function's contract. Exceptions hide the failure path." },
  { id: "q10", chapterId: "functions-errors", level: "intermediate",
    prompt: "When is `defer` executed?",
    choices: ["Immediately, in document order.", "When the program exits.", "When the surrounding function returns, in LIFO order.", "On the next GC cycle."],
    answer: 2, explanation: "Deferred calls run when the enclosing function returns, in reverse order. That's why `defer f.Close()` works on every early return." },
  { id: "q11", chapterId: "functions-errors", level: "intermediate",
    prompt: "What is the difference between `errors.Is` and `errors.As`?",
    choices: ["They are identical.", "`errors.Is` checks for a sentinel value match in the chain; `errors.As` unwraps to a target type.", "`errors.As` is deprecated.", "`errors.Is` only works on stdlib errors."],
    answer: 1, explanation: "`errors.Is` is for sentinel errors like `io.EOF`. `errors.As` extracts a typed error from the chain so you can read its fields." },
  { id: "q12", chapterId: "slices-maps-structs", level: "intermediate",
    prompt: "You do `b := a[1:3]` then modify `b[0]`. What happens to `a`?",
    choices: ["Nothing — slices are deep-copied.", "`a[1]` is also modified because both share the backing array.", "The program panics.", "`a` is reallocated."],
    answer: 1, explanation: "Sub-slicing shares the underlying array. Use `slices.Clone` or `copy` for an independent copy." },
  { id: "q13", chapterId: "slices-maps-structs", level: "intermediate",
    prompt: "Why does writing to a nil map panic?",
    choices: ["Maps are immutable.", "A nil map has no backing hash table; writes require one.", "Only string keys work on nil maps.", "Map writes always panic in debug mode."],
    answer: 1, explanation: "A nil map returns zero values for reads (safe) but panics on writes because there's no hash table. Always `make(map[K]V)` before writing." },
  { id: "q14", chapterId: "interfaces", level: "advanced",
    prompt: "How does a Go type declare that it implements an interface?",
    choices: ["With an `implements` keyword.", "It doesn't — if the method set matches, the type satisfies the interface implicitly.", "By embedding the interface in the struct.", "By registering in an `init()` block."],
    answer: 1, explanation: "Structural (implicit) satisfaction is the defining feature. The producing package doesn't need to know about the interface." },
  { id: "q15", chapterId: "interfaces", level: "advanced",
    prompt: "Can a value `T` satisfy an interface that requires a pointer receiver method on `*T`?",
    choices: ["Yes, Go promotes pointer methods to values.", "No — `T` only has value receiver methods; `*T` has both.", "Only if `T` is a struct.", "Yes, with an explicit cast."],
    answer: 1, explanation: "`*T` includes both value and pointer receiver methods. `T` only has value receiver methods. This is why you often need to pass `&myStruct` to an interface parameter." },
  { id: "q16", chapterId: "goroutines-channels", level: "advanced",
    prompt: "What happens if you send on a closed channel?",
    choices: ["The send is silently dropped.", "The goroutine blocks.", "A panic.", "The channel is reopened."],
    answer: 2, explanation: "Sending on a closed channel panics. Only the sender closes, and only when no more sends will happen." },
  { id: "q17", chapterId: "goroutines-channels", level: "advanced",
    prompt: "What does an unbuffered channel guarantee that a buffered channel with capacity 10 does not?",
    choices: ["Unbuffered channels are faster.", "An unbuffered send blocks until a receiver is ready — it's a synchronization point.", "Unbuffered channels never panic.", "Buffered channels can't be used with select."],
    answer: 1, explanation: "Unbuffered channels are a rendezvous. The send completes only when the receive completes." },
  { id: "q18", chapterId: "context-and-concurrency-patterns", level: "expert",
    prompt: "Why is `defer cancel()` the standard pair for `ctx, cancel := context.WithTimeout(...)`?",
    choices: ["It's cosmetic.", "Without cancel, the timer goroutine and context tree node leak until the deadline fires.", "`cancel` is required to read `ctx.Err()`.", "It propagates the context to child goroutines."],
    answer: 1, explanation: "Every WithTimeout/WithCancel allocates resources reclaimed only when cancel runs. `go vet` warns if missing." },
  { id: "q19", chapterId: "context-and-concurrency-patterns", level: "expert",
    prompt: "When should you prefer `sync.Mutex` over a channel?",
    choices: ["Always.", "When protecting a shared data structure (cache, counter) where ownership doesn't transfer.", "Never — channels replace all mutexes.", "Only in single-goroutine programs."],
    answer: 1, explanation: "Channels model ownership transfer. Mutexes protect shared state accessed concurrently. Both have their place; choose by problem shape." },
  { id: "q20", chapterId: "production-go", level: "expert",
    prompt: "What is the role of the `internal/` directory in a Go module?",
    choices: ["Purely conventional.", "Packages under `internal/` can only be imported by code rooted at its parent — compiler enforced.", "Where `go mod tidy` stores cached deps.", "The only place `package main` may live."],
    answer: 1, explanation: "`internal/` is compiler-enforced, not stylistic. It lets you ship a small public API while organizing the rest freely." },
  { id: "q21", chapterId: "production-go", level: "expert",
    prompt: "What does `go test -race ./...` add beyond a normal test run?",
    choices: ["Faster execution.", "Memory instrumentation that detects concurrent data races at runtime.", "Fuzz testing.", "Benchmark output."],
    answer: 1, explanation: "The race detector instruments memory accesses and reports when two goroutines access the same variable concurrently without synchronization." },
  { id: "q22", chapterId: "generics", level: "advanced",
    prompt: "What does `~int` mean inside a type constraint?",
    choices: ["Approximately int, allowing small differences.", "Any type whose underlying type is int, including user-defined types like `type UserID int`.", "Pointer to int.", "int with nullable semantics."],
    answer: 1, explanation: "The `~` prefix means 'underlying type'. Without it only the exact type `int` satisfies; with it, `type MyInt int` also satisfies." },
  { id: "q23", chapterId: "generics", level: "advanced",
    prompt: "When should you prefer a generic function over an `any` interface parameter?",
    choices: ["Never — any is simpler.", "When you need the return type to match the input type, or want compile-time type safety without type assertions at the call site.", "Only for numeric algorithms.", "Generics are always faster so always prefer them."],
    answer: 1, explanation: "Generics preserve type information through the call. `any` erases it, requiring assertions. Use generics for containers and algorithms; interfaces for behaviour." },
  { id: "q24", chapterId: "oop-patterns", level: "advanced",
    prompt: "What problem does the functional options pattern solve?",
    choices: ["It replaces interfaces.", "It provides a backward-compatible, self-documenting way to pass optional configuration without large config structs or overloaded constructors.", "It eliminates the need for structs.", "It is only used for HTTP clients."],
    answer: 1, explanation: "Adding a new option never breaks existing callers. Call sites read like `WithTimeout(5s)` instead of positional magic numbers." },
  { id: "q25", chapterId: "oop-patterns", level: "advanced",
    prompt: "What is the difference between embedding and inheritance in Go?",
        choices: ["They are the same thing.", "Embedding promotes fields/methods for code reuse; there is no polymorphism — a Dog is not an Animal for type-checking purposes.", "Embedding is slower.", "Inheritance exists via the `extends` keyword."],
    answer: 1, explanation: "Go has no inheritance. Embedding is composition — the embedded type's methods are promoted. Interfaces handle polymorphism separately." },
  { id: "q26", chapterId: "file-io-encoding", level: "expert",
    prompt: "Why should you wrap `os.Open` in `bufio.NewScanner` for line-by-line reading?",
    choices: ["For UTF-8 support.", "Unbuffered reads issue one syscall per call; bufio batches into 4–64 KB blocks — orders of magnitude fewer syscalls.", "Required by the os package.", "For thread safety."],
    answer: 1, explanation: "Syscall overhead dominates on line-oriented data. bufio amortizes it across a large buffer." },
  { id: "q27", chapterId: "file-io-encoding", level: "expert",
    prompt: "What does the struct tag `json:\"score,omitempty\"` do?",
    choices: ["Maps Score to 'score' only.", "Maps the field to key 'score' in JSON and omits it entirely when the value is zero.", "Enables optional validation.", "Makes the field read-only."],
    answer: 1, explanation: "`omitempty` skips the field in the JSON output if it equals the zero value (0, \"\", false, nil). Useful for sparse records." },
  { id: "q28", chapterId: "data-pipelines", level: "expert",
    prompt: "How do buffered channels implement backpressure in a pipeline?",
    choices: ["They don't — channels have no backpressure.", "When the buffer is full the sender blocks, naturally pacing the producer to the consumer's speed.", "They drop excess items.", "They spawn more goroutines automatically."],
    answer: 1, explanation: "A full buffered channel blocks the producer. This propagates slowness upstream — the definition of backpressure." },
  { id: "q29", chapterId: "data-pipelines", level: "expert",
    prompt: "Why should pipeline stage functions use directional channel types (`<-chan T`, `chan<- T`)?",
    choices: ["For performance.", "To encode ownership in the type system — the compiler prevents the wrong goroutine from sending or closing a channel.", "Required by the runtime.", "Only needed with generics."],
    answer: 1, explanation: "Directional types are compiler-enforced ownership. A receive-only `<-chan T` can't be closed by the receiver — preventing a common bug." },
  { id: "q30", chapterId: "databases", level: "expert",
    prompt: "Why must you always check `rows.Err()` after iterating `sql.Rows`?",
    choices: ["It's stylistic.", "Errors during iteration (network failure, query timeout) surface in Err(), not in Next() returning false.", "rows.Err() closes the connection.", "Required for prepared statements."],
    answer: 1, explanation: "`rows.Next()` returns false on both EOF and error. Only `rows.Err()` tells you which it was." },
  { id: "q31", chapterId: "databases", level: "expert",
    prompt: "Why is `defer tx.Rollback()` idiomatic even when you call `tx.Commit()` at the end?",
    choices: ["It's redundant but harmless.", "After Commit, Rollback is a no-op; on any early return it cleans up the open transaction.", "It commits first then rolls back.", "Required by all SQL drivers."],
    answer: 1, explanation: "The defer fires on every exit path. If Commit succeeded, Rollback is a no-op. If the function returned early, Rollback releases the connection." },
  { id: "q32", chapterId: "databases", level: "expert",
    prompt: "What makes DuckDB better than PostgreSQL for analytics queries over Parquet files?",
    choices: ["DuckDB has ACID transactions.", "DuckDB is in-process and columnar — it reads only needed columns, vectorizes execution, and queries Parquet directly with no network overhead.", "PostgreSQL can't read Parquet.", "DuckDB supports more SQL."],
    answer: 1, explanation: "In-process eliminates network latency. Columnar storage skips irrelevant columns. Vectorized execution processes batches. All three compound for 10-100× analytics speedup." },
  { id: "q33", chapterId: "http-api-capstone", level: "expert",
    prompt: "What did Go 1.22 add to `http.ServeMux`?",
    choices: ["WebSocket support.", "Method-specific routing (`GET /path`) and path parameters (`/users/{id}`) via `r.PathValue()`.", "Automatic JSON encoding.", "Middleware chaining."],
    answer: 1, explanation: "Before 1.22, ServeMux only matched path prefixes with no method dispatch or path params — requiring third-party routers. 1.22 closes most of that gap." },
  { id: "q34", chapterId: "http-api-capstone", level: "expert",
    prompt: "What does `server.Shutdown(ctx)` do that a simple process kill does not?",
    choices: ["It's identical to killing the process.", "It stops accepting new connections and waits for in-flight requests to complete before closing, up to the context deadline.", "It flushes disk caches.", "It deregisters the service from a registry."],
    answer: 1, explanation: "Graceful shutdown drains in-flight requests. A kill cuts them off mid-response, causing client errors and potentially corrupting state." }
];
